### PR TITLE
Add the instruction to disable the fqdns grain on the registerd systems(bsc#1134860)

### PR DESCRIPTION
**Pull request by admd**
Add the instruction to disable the fqdns grain on the registered systems

### CODE REVIEW

**Comment by admd** [comment]
> Not sure whether this is the right chapter. To me it's not really related to rate limiting, but generally notable for performance and in particular in high scale cases.

Yeah, I wasn't sure either and couldn't find more suitable chapter. The only reason I put it there because it was kind of close to another kind of similar scenario. I can, of course, move it to a more appropriate chapter if Doc team could point me to.

**Comment by Loquacity** [comment]
> > Not sure whether this is the right chapter. To me it's not really related to rate limiting, but generally notable for performance and in particular in high scale cases.
> 
> Yeah, I wasn't sure either and couldn't find more suitable chapter. The only reason I put it there because it was kind of close to another kind of similar scenario. I can, of course, move it to a more appropriate chapter if Doc team could point me to.

It looks like troubleshooting to me ...

**Comment by moio** [comment]
@Loquacity this is not really troubleshooting, it's a best practice for all users that onboarded any minion before the latest version. It can be seen as an optimization, and will be cited in the release notes.

It only affects minions, in principle independently whether they are connected to an Uyuni/SUSE Manager Server or not. In practice, this is especially useful if they are.

**Comment by Loquacity** [comment]
> @Loquacity this is not really troubleshooting, it's a best practice for all users that onboarded any minion before the latest version. It can be seen as an optimization, and will be cited in the release notes.
> 
> It only affects minions, in principle independently whether they are connected to an Uyuni/SUSE Manager Server or not. In practice, this is especially useful if they are.

So I think we're agreeing on large scale/tuning then?

**Comment by moio** [comment]
> So I think we're agreeing on large scale/tuning then?

FMPOV, only if we do not have a better place, as this is useful regardless of scale.

**Comment by Loquacity** [comment]
> > So I think we're agreeing on large scale/tuning then?
> 
> FMPOV, only if we do not have a better place, as this is useful regardless of scale.

So what about the client config guide then?

**Comment by moio** [comment]
Sounds much better!

**Comment by Loquacity** [comment]
@admd Do you need some help with this one?

**Comment by admd** [comment]
Hi @Loquacity, I am so sorry. I was of the view that doc-squad will take care of moving this text to the correct part and totally forgot about this, my fault. Can you please guide me to the page in the client config guide where I should add this text?

**Comment by Loquacity** [comment]
> Hi @Loquacity, I am so sorry. I was of the view that doc-squad will take care of moving this text to the correct part and totally forgot about this, my fault. 

No problem, I'm happy to take this on if that's what you would prefer.

> Can you please guide me to the page in the client config guide where I should add this text?

If you don't think it belongs in troubleshooting, then I would make it into its own section, which can go into the nav around about the same place as SSM stuff.

Let me know if you want a hand.

**Comment by admd** [comment]
Hi @Loquacity , I have moved the text to the troubleshooting page in client config.

**Comment by Loquacity** [comment]
> Hi @Loquacity , I have moved the text to the troubleshooting page in client config.

In this repo, or in the Uyuni repo?

**Comment by Loquacity** [comment]
Please review https://github.com/uyuni-project/uyuni-docs/pull/28

**Pull request closed without merging**
