### PR TITLE
remove client OSses which are out of maintenance

### PR DESCRIPTION
**Pull request by kkaempf**

### CODE REVIEW

**Comment by jcayouette** [comment]
Thanks!

**Comment by kkaempf** [comment]
https://www.suse.com/lifecycle is the official resource

We might want to add a "best effort" notice about unsupported OSses

**Comment by kkaempf** [comment]
Something like

"About versions out-of-mainenance

We acknowledge the need to manage older versions or service pack level of SLES or RHEL in order to bring them to a supported level with the help of SUSE Manager. SUSE Manager engineering will try to provide 'best effort' support in case of problems. Please talk to your SUSE consultant or sales representative."

**Comment by jcayouette** [comment]
Once the adoc effort is complete we will get a note added.

**Pull request closed without merging**
