### PR TITLE
virtualiazation documentation update

### PR DESCRIPTION
**Pull request by cbosdo**
This PR documents uyuni-project/uyuni#5
An update of image ``system_details_traditional_virtualization_details.png``

### CODE REVIEW

**Comment by keichwa** [comment]
Thanks for the update and special thanks for attacking the xml2adoc conversation artifacts!  If nobody takes action, I can probably review and merge it next week.  Great work, you did not put in obstacles, but there are still some bits from the conversation that I'd like to eliminate.  BTW, we also have ``[package]`` as a tag for package names.

**Comment by cbosdo** [comment]
@keichwa Thanks for the info. Just note that the [resource] use was here before: I just changed the formatting of the text. But I can change it too if you need it

**Comment by keichwa** [comment]
Cederic, I hope you can agree with the adoc related changes I committed.

**Comment by cbosdo** [comment]
@keichwa looks good to me so far, no real content change FWICT

**Pull request merged**
