### PR TITLE
Removed SCC credentials step from YaST install.

### PR DESCRIPTION
**Pull request by Loquacity**
https://github.com/SUSE/spacewalk/issues/6968
https://github.com/SUSE/spacewalk/issues/4424

### CODE REVIEW

**Comment by Loquacity** [comment]
> I think we should do a test installation to see whether the procedure is still fine.

Probably sensible, but I don't have the appropriate test setup here. Are you able to do that?

**Comment by Loquacity** [comment]
> > I think we should do a test installation to see whether the procedure is still fine.
> 
> Probably sensible, but I don't have the appropriate test setup here. Are you able to do that?

In case you don't get to do this in the next day or two, I'm now looking at the unified installer in https://github.com/SUSE/spacewalk/issues/7238 so can test this once I have something up and running.

**Comment by Loquacity** [comment]
Update: this whole section is going to change, so I'm going to merge this one to prevent conflicts.

**Comment by keichwa** [comment]
> Update: this whole section is going to change, so I'm going to merge this one to prevent conflicts.

Yes, makes sense.  And yes, I'll hopefully have time to do test installations.

**Pull request merged**
