### PR TITLE
Added group states info

### PR DESCRIPTION
**Pull request by Loquacity**
https://wiki.microfocus.com/index.php/SUSE_Manager/SystemGroupStates

### CODE REVIEW

**Comment by Loquacity** [comment]
https://github.com/SUSE/spacewalk/issues/5335

**Comment by Loquacity** [comment]
"Highstate" is new to me, so happy to be guided by you. Would you usually capitalise it, too? As for "file roots" I really want that to be two words, but I have no data.

**Comment by keichwa** [comment]
Lana Brindley <notifications@github.com> writes:

> "Highstate" is new to me, so happy to be guided by you. Would you
> usually capitalise it, too?

" grep -i highstate adoc/*.adoc" produces mixed results.  I'm not sure.
I guess it's a Salt term.  We should check the Salt docs.

> As for "file roots" I really want that to be two words, but I have no
> data.

I simple do not know what "file root"/"fileroot" means...

-- 
Karl Eichwalder            SUSE Linux GmbH
PES / Documentation        Maxfeldstraße 5
                           90409 Nürnberg, Germany
GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg)

**Comment by Loquacity** [comment]
https://docs.saltstack.com/en/latest/ref/states/highstate.html would indicate that it's one word, not capitalised. So you were right :)

Re: file root, it probably should be 'root directory' but I was using the terminology from the wiki.

**Comment by keichwa** [comment]
Lana Brindley <notifications@github.com> writes:

> Re: file root, it probably should be 'root directory' but I was using
> the terminology from the wiki.

Ah, I see.  Yes, in this case I'd prefer 'root directory'.

-- 
Karl Eichwalder            SUSE Linux GmbH
PES / Documentation        Maxfeldstraße 5
                           90409 Nürnberg, Germany
GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg)

**Pull request merged**
