### PR TITLE
Admin content review #8361 ke

### PR DESCRIPTION
**Pull request by keichwa**
WIP!

### CODE REVIEW

**Comment by keichwa** [comment]
I'll create a PR per chapter.  This one is ready for review.

**Comment by Loquacity** [comment]
LGTM, but why are you marking up Dockerfile?

**Comment by keichwa** [comment]
Lana Brindley <notifications@github.com> writes:

> LGTM, but why are you marking up Dockerfile?

Because it is capitalized.  Maybe, we'd better writer "dockerfile"
without capitalization.  Here is how the "make" documentation starts:

> 2 An Introduction to Makefiles
> ******************************

> You need a file called a "makefile" to tell 'make' what to do.  Most
> often, the makefile tells 'make' how to compile and link a program.

>   In this chapter, we will discuss a simple makefile that describes how
> to compile and link a text editor which consists of eight C source files
> and three header files. 

-- 
Karl Eichwalder            SUSE Linux GmbH
PES / Documentation        Maxfeldstraße 5
                           90409 Nürnberg, Germany
GF: Felix Imendörffer, Mary Higgins, Sri Rasiah, HRB 21284 (AG Nürnberg)

**Comment by Loquacity** [comment]
> Lana Brindley <notifications@github.com> writes:
> LGTM, but why are you marking up Dockerfile?
> Because it is capitalized. Maybe, we'd better writer "dockerfile" without capitalization. Here is how the "make" documentation starts:
> […](#)
> 2 An Introduction to Makefiles ****************************** You need a file called a "makefile" to tell 'make' what to do. Most often, the makefile tells 'make' how to compile and link a program. In this chapter, we will discuss a simple makefile that describes how to compile and link a text editor which consists of eight C source files and three header files.


oof, no I wouldn't do this. We don't need to treat it as a proper noun, it just makes it hard for readers to parse.

**Comment by keichwa** [comment]
On 2019-07-26 03:39, Lana Brindley wrote:
> oof, no I wouldn't do this. We don't need to treat it as a proper
> noun, it just makes it hard for readers to parse.

Ok, but phrases such as "Edit the Makefile" oder "Edit the Dockerfile" 
are bad.
We either should write "Edit the dockerfile" or "Edit Dockerfile" or 
"Edit the
Dockerfile file".

We often say "Edit the salt.conf file." (with markup, btw). I'd probably 
prefer
"Edit salt.conf" and thus "Edit Dockerfile".

-- 
Karl Eichwalder

**Comment by Loquacity** [comment]
> On 2019-07-26 03:39, Lana Brindley wrote: oof, no I wouldn't do this. We don't need to treat it as a proper noun, it just makes it hard for readers to parse.
> Ok, but phrases such as "Edit the Makefile" oder "Edit the Dockerfile" are bad. We either should write "Edit the dockerfile" or "Edit Dockerfile" or "Edit the Dockerfile file". We often say "Edit the salt.conf file." (with markup, btw). I'd probably prefer "Edit salt.conf" and thus "Edit Dockerfile".

What's wrong with "Edit the dockerfile"?

**Comment by keichwa** [comment]
On 2019-07-26 07:47, Lana Brindley wrote:
>> On 2019-07-26 03:39, Lana Brindley wrote: oof, no I wouldn't do this. 
>> We don't need to treat it as a proper noun, it just makes it hard for 
>> readers to parse.
>> Ok, but phrases such as "Edit the Makefile" oder "Edit the Dockerfile" 
>> are bad. We either should write *"Edit the dockerfile"* or "Edit 
>> Dockerfile" or "Edit the Dockerfile file". We often say "Edit the 
>> salt.conf file." (with markup, btw). I'd probably prefer "Edit 
>> salt.conf" and thus "Edit Dockerfile".
> 
> What's wrong with "Edit the dockerfile"?

Nothing ;)  I listed that variant as the first option.  Trying to add 
bold markers via mail...

-- 
Karl Eichwalder

**Comment by keichwa** [comment]
> Trying to add bold markers via mail...

did not **fly**.  Editing...

**Comment by keichwa** [comment]
I removed markup from "dockerfile".  Ready for review!

**Pull request merged**
