### PR TITLE
Update to fix some build errors

### PR DESCRIPTION
**Pull request by Loquacity**
https://github.com/SUSE/spacewalk/issues/8899
https://github.com/SUSE/spacewalk/issues/8900

### CODE REVIEW

**Comment by Loquacity** [comment]
That fixes all the build errors on my system.

**Comment by paususe** [comment]
Ugh, sorry I opened these issues on the wrong repo

**Comment by Loquacity** [comment]
> Ugh, sorry I opened these issues on the wrong repo

All good, we all do it! There's now a much easier way to transfer them, which is nice :heart:

**Comment by Loquacity** [comment]
@paususe Just on a point of administration: in the docs team, we have a policy not to merge each other's PRs. Feel free to just hit approve and I'll merge it :)

**Pull request merged**
