### PR TITLE
Feat: add OS Image documentation

### PR DESCRIPTION
**Pull request by mbologna**
NOTE: **We will ping you whenever this has to be merged, thanks!**

- Restore visibility of OS Image documentation
- Add documentation about pillars
- Add documentation about rhn.conf enablement of OS image building

### CODE REVIEW

**Comment by keichwa** [comment]
@mbologna I'd like apply some very minor cosmetic changes such as capitalization in section titles (so-called title style).  I'm not sure whether this would result in another Frankenstein PR and I'd better wait with it ;-P

**Comment by mbologna** [comment]
@keichwa :rofl: I made the Frankenstein PR, not you, do not worry!
I suggest: if the things you want to change are already inside `develop` and not modified in this PR (not highlighted lines in "Files changed"), please modify them in `develop` branch. Otherwise feel free to modify this PR. thanks!

**Comment by keichwa** [comment]
Ok, done.

**Comment by keichwa** [comment]
I tried to resolve recently introduced conflicts.  Hope I got it right.

**Comment by keichwa** [comment]
@mbologna  @aaannz
The last days I read this chapter and applies some changes.

But still some sections are too complicate for me and some info is missing.  For example, there are general statements such as "Example scripts are provided in the following sections." Please reference them either via proper labels or pseudo labels within comments, for example:
`// ###example-script-1###`

**Comment by mbologna** [comment]
@keichwa I added a reference for the example script. Not sure if I used the correct syntax and if we need to point out other scripts (the full example is only this one). Let me know if I need to add other infos

**Comment by mbologna** [comment]
In this sprint, we are going to merge OS Image building feature for 3.2 (part of the future MU).
IMHO the documentation is ready to be unveiled. Should we merge this PR and unveil the doc?

**Comment by mcalmer** [comment]
Please wait at least until docs are submitted for the 3.2 MU. As the code is not in this MU it would be confusing to see docs about it :-)

**Comment by keichwa** [comment]
@mbologna according to https://github.com/SUSE/spacewalk/pull/4494 the feature is still not merged (I hope this is the right one).

**Comment by mbologna** [comment]
#4494 has been merged. Do you need help with the conflicts?

**Comment by keichwa** [comment]
Michele Bologna <notifications@github.com> writes:

> #4494 has been merged. Do you need help with the conflicts?

Thanks for merging!  I'll resolve the conflicts, np.

-- 
Karl Eichwalder            SUSE Linux GmbH
PES / Documentation        Maxfeldstraße 5
                           90409 Nürnberg, Germany
GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg)

**Comment by Loquacity** [comment]
I just went through and fixed a few things I noticed, wording, typos, etc.

**Comment by jcayouette** [comment]
I am still seeing conflicts?

**Comment by keichwa** [comment]
Joseph Cayouette <notifications@github.com> writes:

> I am still seeing conflicts?

I'm not able to resolve them without merging.  Help appreciated, though
;)


-- 
Karl Eichwalder            SUSE Linux GmbH
PES / Documentation        Maxfeldstraße 5
                           90409 Nürnberg, Germany
GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg)

**Pull request merged**
