### PR TITLE
Add docs about mgr-sign-metadata-ctl

### PR DESCRIPTION
**Pull request by mateiw**
Docs about managing repo metadata signing using the new tool `mgr-sign-metadata-ctl`.

### CODE REVIEW

**Comment by Loquacity** [comment]
This needs to be opened against the /beta1 branch. The adoc/advanced_topics_security.adoc file can now be found at /modules/administration/pages/security.adoc

**Comment by cbbayburt** [comment]
@Loquacity, @mateiw, I can't follow this. Has this been implemented for beta1?

**Comment by Loquacity** [comment]
> @Loquacity, @mateiw, I can't follow this. Has this been implemented for beta1?

Doesn't  appear so. I'll do a PR against the right branch now.

**Comment by Loquacity** [comment]
https://github.com/SUSE/doc-susemanager/pull/388

**Pull request closed without merging**
