### PR TITLE
Split Contact Methods

### PR DESCRIPTION
**Pull request by Loquacity**
https://github.com/SUSE/spacewalk/issues/9082

### CODE REVIEW

**Comment by Loquacity** [comment]
Can confirm this builds :+1:

**Comment by Loquacity** [comment]
TODO: Edit the intro file.

**Comment by Loquacity** [comment]
Can confirm this builds :+1:

**Comment by Loquacity** [comment]
> Assuming, it's just a split.

Yeah, it's a straight split, no other editing except for the intro. There, I used the first para of each section, then lightly edited it.

**Comment by keichwa** [comment]
Lana Brindley <notifications@github.com> writes:

> Yeah, it's a straight split, no other editing except for the
> intro. There, I used the first para of each section, then lightly edited
> it.

Thanks, nicely done! :+1:

-- 
Karl Eichwalder            SUSE Software Solutions Germany GmbH
PES / Documentation        Maxfeldstraße 5
                           90409 Nürnberg, Germany
Geschäftsführer: Felix Imendörffer (HRB 247165, AG München)

**Pull request merged**
