### PR TITLE
WIP: Install overhaul for Unified Installer

### PR DESCRIPTION
**Pull request by Loquacity**
Part 2 of https://github.com/SUSE/doc-susemanager/pull/367

### CODE REVIEW

**Comment by Loquacity** [comment]
> No opinion. What a big removal! Are we sure that proxies are still covered?

None of this content was deleted, just moved. It's all in either the Install Guide or the Client Cfg.

**Comment by Loquacity** [comment]
I've added ifeval statements in to conditionalise suma/uyuni, but need to check with @jcayouette about how to make these actually work.

**Comment by jcayouette** [comment]
I added a new conditional attribute to both of our product playbooks:
- [X] suma-site.yml
- [X] uyuni-site.yml

**suma-site.yml**
```
asciidoc:
  attributes:
    productname: 'SUSE Manager'
    suma-content: true
```

**uyuni-site.yml**
```
asciidoc:
  attributes:
    productname: 'SUSE Manager'
    suma-content: false
```

This means you may now use the following conditional for suma only content in our nav lists.

```
** Installation
ifeval::[{suma-content} == true]
*** xref:install-server-unified.adoc[Installing SUSE Manager Server]
*** xref:install-proxy-unified.adoc[SUSE Manager 4.0 Proxy]
endif::[]
*** xref:install-vm.adoc[Install VM]
*** xref:install-server.adoc[Install Server]
*** xref:install-proxy.adoc[Install Proxy]
*** xref:install-zsystems.adoc[Install IBM zSystems]
** Setting Up
*** xref:server-setup.adoc[Server Setup]
*** xref:proxy-setup.adoc[Proxy Setup]
```

I also cleaned up the nav list for our configuration guide, some items were at the incorrect list level. Nothing serious. :)

**Comment by jcayouette** [comment]
resolved conflicts.

**Comment by Loquacity** [comment]
I'm going to merge this one for now. We'll probably need to  do more work to this guide before 4.0, but it's getting closer, and we can safely say that the unified installer is documented now. Thanks for the  help @jcayouette :)

**Comment by jcayouette** [comment]
Np! I like the new syntax, great idea Lana :)

**Pull request merged**
