### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by dvosburg**
This system groups under user details makes more sense - there ARE actual groups.  In the current doc it is confusing because there are no reference-able system groups to use for user restriction.

### CODE REVIEW

**Comment by Loquacity** [comment]
Thanks @dvosburg Did you mean to include this image in the text somewhere?

**Comment by dvosburg** [comment]
Well, it is referenced in the text with an image that has NO system groups
at all...

**Comment by Loquacity** [comment]
Where?

**Comment by dvosburg** [comment]
https://www.suse.com/documentation/suse-manager-4/4.0/suse-manager/reference/users/user-details.html#s4-usr-active-details-sysg

**Comment by Loquacity** [comment]
OK, that's working properly now:
Screenshot from a local build of this branch:

image

**Pull request merged**
