### PR TITLE
Content Review - Client Cfg - Part 2

### PR DESCRIPTION
**Pull request by Loquacity**
https://github.com/SUSE/spacewalk/issues/8362

### CODE REVIEW

**Comment by Loquacity** [comment]
> I do not know whether we can already provide info about rhel 8.

Not last I checked. I think we're a while away from having any kind of RHEL 8 updates in SUMA.

**Comment by cbbayburt** [comment]
> I do not know whether we can already provide info about rhel 8.

You can track the status here if you'd like: https://github.com/SUSE/spacewalk/issues/6420

**Comment by keichwa** [comment]
On 2019-08-09 11:25, Can Bulut Bayburt wrote:
>> I do not know whether we can already provide info about rhel 8.
> 
> You can track the status here if you'd like:
> https://github.com/SUSE/spacewalk/issues/6420

Thanks for the pointer!  It looks as if there is still some way to
go.

-- 
Karl Eichwalder

**Comment by Loquacity** [comment]
And ... we're done!

**Pull request merged**
