### PR TITLE
fixed broken xref

### PR DESCRIPTION
**Pull request by jcayouette**

### CODE REVIEW

**Comment by Loquacity** [comment]
lol, I fixed that in a different PR ;)

**Comment by keichwa** [comment]
Lana Brindley <notifications@github.com> writes:

> lol, I fixed that in a different PR ;)

Yes, I also had that feeling but was not able finding yours without
spending too much time ;)

-- 
Karl Eichwalder            SUSE Software Solutions Germany GmbH
PES / Documentation        Maxfeldstraße 5
                           90409 Nürnberg, Germany
Geschäftsführer: Felix Imendörffer (HRB 36809, AG Nürnberg)

**Comment by Loquacity** [comment]
> Lana Brindley <notifications@github.com> writes:
> lol, I fixed that in a different PR ;)
> Yes, I also had that feeling but was not able finding yours without spending too much time ;)

Yeah, because I was lazy and fixed it in your PR, without creating a new one of my own. That'll learn me :wink:

**Comment by keichwa** [comment]
On 2019-10-31 01:21, Lana Brindley wrote:

> Yeah, because I was lazy and fixed it in your PR, without creating a
> new one of my own. That'll learn me :wink:

;) Lazy or not, this is often a good strategy for thus minor stuff.
Help speeding up our turnaround cycles (or whatever the word is to
describe what I mean). :happy:

-- 
Karl Eichwalder

**Pull request merged**
