### PR TITLE
[WIP] SUSE Manager for Retail reference documentation

### PR DESCRIPTION
**Pull request by aaannz**
This is still in WIP, but feel free to add commits.

I am not sure if this will be distributed as a standalone book or part of the SUMA documentation.

Missing parts:

- [ ]  Saltboot process
- [ ] Image customization
- [ ] Retail specific settings for generic formulas (DNC, TFTP, PXE, VSFTP)

### CODE REVIEW

**Comment by jcayouette** [comment]
I have a few thoughts I think we should address/clarify before merging,

- Reference refers to the SUSE Manager WebUI, In contrast this should probably be renamed to "SUSE Manager for Retail" or some other similar format.
- Instead of the {smr} entity I propose we stick with {productname} and simply generate docs at build time, with a separate included section for retail. This means you would have the exact same data "no duplication" of SUSE Manager docs, and the maintained "retail" doc with simply an entity change.
- Let's find out how we may best distribute this,  how does the retail PO feel about the above idea? After these have been discussed then we can merge it. :)

Currently we can maintain a Makefile containing our build commands. We could just following this logic for simplicities sake:

make suma - :productname: SUSE Manager
make uyuni - :productname: Uyuni
make retail - :productname: SUSE Manager for Retail

The retail doc would not be included in Uyuni/suma built documentation by a conditional statement.

P.S. I realize last week there was a mailing list discussion but I was unable to follow as effectively as I would have liked due to HA priority. Ill try and catch up as time permits.

**Comment by Loquacity** [comment]
This is a great start for content, thank you @aaannz! <3

Before we get too far down this road, though, we need to sort a few things out:
[ ] The title and structure of this book
[ ] How we are going to handle entities (in this doc, and in the rest of the doc suite). 
[ ] Whether or not we are publishing a Retail-specific documentation suite (in addition to this doc), or just pointing Retail readers to the SUMA docs. 

It's super-important that we get the planning done *before* we start writing content. I am going to create a document to allow us to get started on that, and will add a link here shortly.

**Comment by aaannz** [comment]
Thanks for all the comments. I share all of you concerns.

@jcayouette:
- what reference to Web UI you have in mind? Retail is part of the SUMA, everything is being distributed together and there is no special branding AFAIK. We are basically creating a documentation for a specific use case of SUMA.
- I'll change `{smr}` to `{productname}`
- Distribution question is for @jsrain or @abhinav-puri: Should the Retail documentation be standalone or part of the SUMA?

@Loquacity:
- Indeed, I started it as a reference guide, but this is probably something bigger. Still, it is only a one special use case to SUMA. I started with content immediately so that QA guys can have some starting point for their work.

**Comment by keichwa** [comment]
Ondřej Holeček <notifications@github.com> writes:

> - I'll change `{smr}` to `{productname}`

I'd recommend to stick with `{smr}`, at least for moment.  It's easy to
change it later, if needed.

> - Indeed, I started it as a reference guide, but this is probably
> something bigger.

I see your point, but ATM we use the term "reference" resp. "Reference
Guide" for the document that describes the SUMA Web UI, one by one menu
item.  Thus I'd like us to call the document about the Retail product
that you started, just "SUMA for Retail" or "SUMA for Retail Guide", or
something similar.

> Still, it is only a one special use case to SUMA. I started with
> content immediately so that QA guys can have some starting point for
> their work.

Yes, I also appreciate this!  We can re-write part of it or restructure
it later, if we know what we want.  If you have free cycles, please
continue with drafting a "SUMA for Retail Guide" :-)

-- 
Karl Eichwalder            SUSE Linux GmbH
PES / Documentation        Maxfeldstraße 5
                           90409 Nürnberg, Germany
GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg)

**Comment by Loquacity** [comment]
> Indeed, I started it as a reference guide, but this is probably something bigger. Still, it is only a one special use case to SUMA. I started with content immediately so that QA guys can have some starting point for their work.

That's great, I'm sure they appreciate it :)

Once we've got a plan in place (https://github.com/SUSE/doc-susemanager/wiki/SUSE-Manager-for-Retail-Documentation/88847b8cd661e1b3ae96ad889a0f31903e0fa82e) we can create a new doc and put all this straight in there. Thanks for all the hard work <3

**Comment by Loquacity** [comment]
This is now being handled here: https://github.com/SUSE/doc-susemanager/pull/172

**Pull request closed without merging**
