### PR TITLE
Update general-requirements.adoc

### PR DESCRIPTION
**Pull request by keichwa**
per feedback
is this what you mean, @mcalmer ?

### CODE REVIEW

**Comment by keichwa** [comment]
> Yes, somehow. Maybe you can also change line 102/103 . (0750) and (0775) is part of the output of ls.

I think that's already in Lana's change:
```
The output should look like this:

----
(0750) drwxr-x--- 1 postgres postgres /var/lib/pgsql
(0775) drwxrwxr-x 1 wwwrun   www      /var/spacewalk/
----
```

**Comment by mcalmer** [comment]
I wanted to write: (0750) and (0775) is **not** part of the output of ls.

**Comment by keichwa** [comment]
> I wanted to write: (0750) and (0775) is **not** part of the output of ls.

Honestly, I was already wondering whether ls had changed and wanted to test later in the office ;)

**Comment by Loquacity** [comment]
> > I wanted to write: (0750) and (0775) is **not** part of the output of ls.
> 
> Honestly, I was already wondering whether ls had changed and wanted to test later in the office ;)

Heh, I just figured my system was set up differently to yours :P

**Pull request merged**
