### PR TITLE
Add documentation for the new notifications property java.notifications_type_disabled

### PR DESCRIPTION
**Pull request by lneves12**
Add documentation for the PR: https://github.com/uyuni-project/uyuni/pull/329

To be backported to 3.2 and 3.1 as soon as approved.

### CODE REVIEW

**Comment by lneves12** [comment]
Thanks @Loquacity for the wording improvements, it looks better now :)

**Comment by keichwa** [comment]
@lneves12 3.1 is rather behind... I'm wondering whether the complete section about notifications that we now have in our 3.2 documentation is also suitable for 3.1?  Or should I just add the snippet that you committed here:
````
All notification types are enabled by default.
To disable a notification type, open the [path]``/etc/rhn/rhn.conf`` configuration file and edit the [systemitem]``java.notifications_type_disabled`` parameter:

----
# Configure the disablement of notification messages by type - example disabling all notification types
java.notifications_type_disabled = OnboardingFailed,ChannelSyncFailed,ChannelSyncFinished
----
````

**Comment by ncounter** [comment]
>... 3.1 is rather behind... I'm wondering whether the complete section about notifications that we now have in our 3.2 documentation is also suitable for 3.1? Or should I just add the snippet that you committed here:

@keichwa if I remember correctly and I am not wrong, we didn't backported (and we don't want to) to 3.1 both the `java.notifications_lifetime` and `java.notifications_type_disabled` config parameters, so the 3.1 documentation is pretty behind but it is correct. Maybe @lneves12 will double check and confirm.

**Comment by lneves12** [comment]
I backported the Java.notifications_type_disabled to 3.1: 
https://github.com/SUSE/spacewalk/pull/6665/files    Should we revert that? @ncounter 

I am not sure about the java.notifications_lifetime if it was backported or not to 3.1

**Comment by keichwa** [comment]
> I backported the Java.notifications_type_disabled to 3.1:
> https://github.com/SUSE/spacewalk/pull/6665/files Should we revert that? @ncounter
> 
> I am not sure about the java.notifications_lifetime if it was backported or not to 3.1

I updated #310.

**Comment by ncounter** [comment]
@lneves12 no no, there is no need to revert it. It was not required to be backported but it's a nice to have it anyway. Customers will be happy I bet :wink:

**Comment by ncounter** [comment]
@keichwa : to wrap it up

|       | java.notifications_lifetime | java.notifications_type_disabled |
|:-----:|:---------------------------:|:--------------------------------:|
|  3.1  |              ✘              |                 ✔                |
|  3.2  |              ✔              |                 ✔                |
| Uyuni |              ✔              |                 ✔                |

**Comment by keichwa** [comment]
Thanks for clarification!

**Pull request merged**
