### PR TITLE
channel details dialog; #9694

### PR DESCRIPTION
**Pull request by keichwa**
updated image
close https://github.com/SUSE/spacewalk/issues/9694

### CODE REVIEW

**Comment by mseidl** [comment]
Channel name and label may begin with a letter or digit.

That should be the text. somewhere you got an outdated screen shot?  

https://sumas.mgr.suse.de/rhn/channels/manage/Edit.do

That has the correct text.... i just added the screenshot 

create_channel

**Comment by keichwa** [comment]
> Channel name and label may begin with a letter or digit.

AFAICS, mine has this text, too. At least, if I check out the channel-name-#9694-ke branch, modules/reference/assets/images/channels_details_channels.png looks fine to me.

**Comment by mseidl** [comment]
Yours says "channel name or label" and mine says "channel name AND label"

**Comment by keichwa** [comment]
Martin Seidl <notifications@github.com> writes:

> Yours says "channel name or label" and mine says "channel name AND label"

ok, I see.
https://sumas.mgr.suse.de/rhn/channels/manage/Edit.do?cid=101 now also
has your version.

-- 
Karl Eichwalder            SUSE Software Solutions Germany GmbH
PES / Documentation        Maxfeldstraße 5
                           90409 Nürnberg, Germany
Geschäftsführer: Felix Imendörffer (HRB 247165, AG München)

**Pull request merged**
