### PR TITLE
Issue #498: new AT bare metal provisioning section

### PR DESCRIPTION
**Pull request by Loquacity**
From https://wiki.microfocus.com/index.php/SUSE_Manager/NewFeatures2.1/BareMetalProvisioning

### CODE REVIEW

**Comment by Loquacity** [comment]
Note that, after some research, I've gone with "bare metal" over "bare-metal" or "baremetal". If there's an established precedent for a different option, though, I'm happy to change it.

**Comment by kkaempf** [comment]
:+1:

**Comment by keichwa** [comment]
That's probably fine.  in the documentation team, I usually delegate those decisions to @sknorr .

Wondering whether we want to keep the term "bare metal" at all.  ATM, the term "unprovisioned system" is also in use...

**Comment by sknorr** [comment]
Thanks for the hint, @keichwa ... opened https://github.com/SUSE/doc-styleguide/issues/80

Mmh, question though: isn't "bare-metal" just a jargony term for "physical system" (i.e. not a virtualized system)? Or is this used differently in Suma?

**Comment by kkaempf** [comment]
@sknorr yes, "bare metal" and "physical" is almost the same. In SUMA, "bare metal" is mostly used to denote "unprovisioned" (no OS installed) systems, while "physical" refers to "OS running non-virtualized".

(This gets tricky on zSeries or Power systems :wink: )

**Pull request merged**
