### PR TITLE
Scalability: add details on worker_threads

### PR DESCRIPTION
**Pull request by moio**
This incorporates feedback from latest research.

### CODE REVIEW

**Comment by moio** [comment]
Please also cherry-pick to 3.2, thanks!

**Comment by Loquacity** [comment]
LGTM :+1:

**Comment by moio** [comment]
Thanks for the wording fixes!

**Comment by keichwa** [comment]
moio, thanks for your help!  I think you do not have push rights; thus now merging (as approved by Lana).  I'll also add this update to 3.2.

**Pull request merged**
